polar:
  greeting: Welcome to the book catalog from Kubernetes!
spring:
  datasource:
    url: jdbc:postgresql://postgres/polardb_catalog
  flyway:
    url: jdbc:postgresql://postgres/polardb_order
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak/realms/PolarBookshop